[package]
name = "benilla_mobile"
# Version is required by `cargo-apk`, though this value will never change.
version = "0.0.0"
edition = "2024"
description = "Benilla mobile runner"
publish = false
license = "MIT OR Apache-2.0"

[lib]
name = "benilla_mobile"
crate-type = ["lib", "cdylib"]

[dependencies]
benilla-app = { version = "0.1.0", path = "../crates/benilla-app" }
bevy.workspace = true
serde_json = "1.0.151"
variadics_please = "2.0.0"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.22.4"

[target.'cfg(target_os = "ios")'.dependencies]
objc2 = "0.6.4"
objc2-foundation = "0.3.2"
objc2-ui-kit = "0.3.2"
