[package]
name = "benilla_mobile"
# Version is required by `cargo-apk`, though this value will never change.
version = "0.0.0"
edition = "2024"
description = "Benilla mobile runner"
publish = false
license = "MIT OR Apache-2.0"

[lib]
name = "benilla_mobile"
crate-type = ["lib", "cdylib"]

[dependencies]
benilla = { version = "0.1.0", path = "../crates/benilla" }
bevy.workspace = true

[target.'cfg(target_os = "ios")'.dependencies]
objc2 = "0.6.4"
objc2-foundation = "0.3.2"
objc2-ui-kit = "0.3.2"
