//! Terrain-tile texture-array packing for the ADT loader.
//!
//! A tile's ground textures are stacked into one repeating, mipmapped `texture_2d_array`; its
//! per-chunk alpha (blend-weight) and MCSH shadow maps into two more arrays. The fidelity-critical
//! rule (the "C2" invariant, anchored in `wow-5875-re/system/terrain`): the BLP's **authored** mip
//! pyramid is laid in **verbatim** — never CPU-regenerated by averaging texels in gamma byte space,
//! which darkens mid-tones and cools foliage. Off-Elwynn BLPs authored below [`LAYER_TEX_SIZE`] fill
//! the top mips by `NEAREST` upsample (texel replication — gamma-safe, no averaging).
//!
//! # The array's format is a property of the TILE, not of any one texture
//!
//! `Tileset\` is ~98 % S3TC, and 1626 handed the blocks straight to the GPU for model and WMO
//! albedo — but not here, because this lane resamples and stomps texels on the CPU. [`pack_layers`]
//! is what unblocks it: it holds every layer in its **authored** form until the whole tile has been
//! read, then asks one question of the set — *can all of these go up as blocks, together?* One
//! `texture_2d_array` has exactly one format and one mip-0 size, so the answer is all-or-nothing per
//! tile, and the fallback is the decode this lane always did.
//!
//! **The rule earns its narrowness from the install** (censused across all 2 275 textured ADTs):
//! a tile passes when every chosen layer shares one block form, is natively [`LAYER_TEX_SIZE`]² with
//! a full [`LAYER_MIP_COUNT`]-level chain, and needs no matte stomp. That is **87 % of Azeroth's
//! tiles and 92 % of Kalimdor's**, worth 2.5x / 2.9x off their layer bytes. The two obvious
//! extensions were measured and are deliberately **not** built: doing the matte stomp in block space
//! (legal on Bc2/Bc3 — zero the alpha half) buys **0** further tiles, and a block-space power-of-two
//! NEAREST upsample buys **8**. What is left out is left out because it is worth nothing, not
//! because it is hard.

use benilla_formats::{BlpMipChain, BlpTexels};
use bevy::asset::RenderAssetUsages;
use bevy::image::{Image, ImageAddressMode, ImageFilterMode, ImageSampler, ImageSamplerDescriptor};
use bevy::prelude::*;
use bevy::render::render_resource::{
    Extent3d, TextureDataOrder, TextureDimension, TextureFormat, TextureViewDescriptor,
    TextureViewDimension,
};

/// Edge length every layer BLP is uploaded at for the per-tile array (uniform so they share one
/// `texture_2d_array`). The Elwynn A/B target's layer BLPs are all natively 256² with 8 authored mips.
pub(crate) const LAYER_TEX_SIZE: u32 = 256;

/// Per-layer mip count for the array — the authored count at 256². Fewer-mip BLPs repeat the last
/// authored level; sub-256² BLPs upsample (NEAREST) to fill the top.
pub(crate) const LAYER_MIP_COUNT: u32 = 8;

/// Albedo format: non-sRGB `Rgba8Unorm` — the GPU does not linearize on sample, so shader math stays
/// in WoW's gamma/byte space (the RE'd invariant; matches the model/BLP albedo format).
fn color_format() -> TextureFormat {
    TextureFormat::Rgba8Unorm
}

/// The block form's albedo format — the same **non-sRGB** gamma-byte lane [`color_format`] is in
/// (0161). `Bc*RgbaUnormSrgb` would linearize on sample and is the one wrong answer here.
fn block_color_format(texels: BlpTexels) -> TextureFormat {
    match texels {
        BlpTexels::Bc1 => TextureFormat::Bc1RgbaUnorm,
        BlpTexels::Bc2 => TextureFormat::Bc2RgbaUnorm,
        BlpTexels::Bc3 => TextureFormat::Bc3RgbaUnorm,
        BlpTexels::Rgba8Unorm => TextureFormat::Rgba8Unorm,
    }
}

/// One ground texture packed for the per-tile array: its authored mip chain at [`LAYER_TEX_SIZE`]²,
/// concatenated mip-major (level 0 first), `mip_count` levels.
pub(crate) struct LayerTexture {
    pub(crate) chain: Vec<u8>,
    pub(crate) mip_count: u32,
}

/// Pack a BLP's authored mip pyramid into a [`LayerTexture`] for the tile array — authored levels
/// used verbatim (the C2 fix). When the BLP's mip 0 is smaller than `target_size` (off-Elwynn) the
/// top of the chain is NEAREST-upsampled (texel replication, gamma-safe), with the BLP's authored
/// smaller mips slotting into the deeper array levels; when its chain runs out the last authored mip
/// is reused (NEAREST-resampled if the dims still differ).
pub(crate) fn chain_to_layer(blp: BlpMipChain, target_size: u32) -> LayerTexture {
    // **This function cannot take DXT blocks.** It NEAREST-resamples levels to a uniform array size,
    // and [`pack_layers`] stomps the alpha byte after it for the matte case — both are per-texel CPU
    // writes, which is exactly what a block form does not have. That is why the passthrough is a
    // decision taken *before* this point, in [`pack_layers`], rather than a flag threaded through
    // here: a chain that reaches this function has already been ruled out of it (1646).
    debug_assert!(
        blp.is_rgba8(),
        "terrain layer packing indexes texels; it needs a decoded chain"
    );
    let mut chain = Vec::with_capacity(mip_chain_byte_size(target_size, LAYER_MIP_COUNT));
    for level in 0..LAYER_MIP_COUNT {
        let level_w = (target_size >> level).max(1);
        let level_h = level_w; // tilesets are square in 1.12
        if blp.width >= level_w {
            // `BLP width >> j == level_w`  ⟹  `j = log2(BLP width / level_w)`, clamped to the BLP's
            // available mips (if it doesn't go that deep, repeat the last authored level).
            let ratio = (blp.width / level_w).max(1);
            let src_level = (ratio.trailing_zeros() as usize).min(blp.mips.len() - 1);
            let (sw, sh) = blp.mip_size(src_level as u32);
            extend_nearest(&mut chain, &blp.mips[src_level], sw, sh, level_w, level_h);
        } else {
            // Authored smaller than this level — NEAREST-upsample mip 0 (texel replication).
            extend_nearest(
                &mut chain,
                &blp.mips[0],
                blp.width,
                blp.height,
                level_w,
                level_h,
            );
        }
    }
    LayerTexture {
        chain,
        mip_count: LAYER_MIP_COUNT,
    }
}

/// One of a tile's ground textures as it was read, **before** the tile has decided what form its
/// layer array takes — held in its authored form (DXT blocks kept) because that decision belongs to
/// the whole set, not to any one texture. See [`pack_layers`].
pub(crate) struct RawLayer {
    /// The BLP's authored chain, blocks intact ([`benilla_formats::blp_bytes_to_native_chain`]).
    pub(crate) chain: BlpMipChain,
    /// No `_s` specular variant existed for this layer, so its sheen mask must read 0 (matte). On
    /// the decoded path that is an alpha stomp; on the block path it is why the tile is not eligible.
    pub(crate) matte: bool,
}

/// A tile's layer array, packed: LayerMajor bytes plus the format and level count that describe them.
pub(crate) struct PackedLayers {
    pub(crate) data: Vec<u8>,
    pub(crate) format: TextureFormat,
    pub(crate) mip_count: u32,
}

/// The block form this whole tile's layer array can be uploaded in, or `None` if it must be decoded.
///
/// Every clause is a property one `texture_2d_array` cannot vary across its layers, plus the two
/// CPU texel writes this lane used to do unconditionally:
///
/// - **one block form** — an array has one `TextureFormat`, and `Bc1`/`Bc2` are different widths;
/// - **natively [`LAYER_TEX_SIZE`]²** — an array has one mip-0 size, and NEAREST-resampling a level
///   to reach it is a per-texel write blocks do not support;
/// - **a full [`LAYER_MIP_COUNT`]-level chain, every level exactly the size its form implies** — the
///   levels are laid in verbatim, so a short chain would have to repeat one at the wrong size (the
///   same resample again), and a level whose byte count disagreed with the format would corrupt
///   every layer after it rather than fail. `decode_native` pads to whole blocks, so this always
///   holds — it is checked in **release** anyway, because the one bug 1626 shipped was bytes
///   uploaded under a format that implied a different count, and a `debug_assert` cannot catch that
///   in a player's build;
/// - **no matte layer** — zeroing the sheen mask is a per-texel alpha write. (It *is* expressible in
///   Bc2/Bc3 block space — memset the alpha half — and that was measured to buy **zero** further
///   tiles, because a layer with no `_s` variant is a `Bc1` base and its tile is mixed-format anyway.)
///
/// [`crate::gpu_blp::bc_supported`] gates the whole thing, so `WOW_NO_BC=1` and a device without BC
/// both land on the decoded path exactly as before — and so does every headless test, which is what
/// keeps the pixel-reading ones honest.
fn passthrough_form(layers: &[RawLayer], bc_supported: bool) -> Option<BlpTexels> {
    if !bc_supported {
        return None;
    }
    let form = layers.first()?.chain.texels;
    let uniform = form.is_block_compressed()
        && layers.iter().all(|l| {
            l.chain.texels == form
                && !l.matte
                && l.chain.width == LAYER_TEX_SIZE
                && l.chain.height == LAYER_TEX_SIZE
                && l.chain.mips.len() >= LAYER_MIP_COUNT as usize
                && l.chain.mips[..LAYER_MIP_COUNT as usize]
                    .iter()
                    .enumerate()
                    .all(|(i, level)| level.len() == form_level_bytes(form, i as u32))
        });
    uniform.then_some(form)
}

/// Pack a tile's ground textures into its layer array — blocks straight through when the whole set
/// allows it ([`passthrough_form`]), else the decode-resample-stomp path this lane always took.
///
/// `fallback` is layer 0's solid colour: the "this texture would not load" placeholder every tile
/// carries at index 0, which is why it has to be synthesised in whichever form the tile picked.
pub(crate) fn pack_layers(fallback: [u8; 4], layers: Vec<RawLayer>) -> PackedLayers {
    pack(fallback, layers, crate::gpu_blp::bc_supported())
}

/// [`pack_layers`] with the device fact passed in rather than read from the process — so the block
/// path is exercisable in a headless test, where [`crate::gpu_blp::bc_supported`] is always false
/// and would otherwise leave the whole passthrough untested.
fn pack(fallback: [u8; 4], layers: Vec<RawLayer>, bc_supported: bool) -> PackedLayers {
    if let Some(form) = passthrough_form(&layers, bc_supported) {
        let per_layer: usize = (0..LAYER_MIP_COUNT)
            .map(|i| form_level_bytes(form, i))
            .sum();
        let mut data = Vec::with_capacity((layers.len() + 1) * per_layer);
        data.extend_from_slice(&solid_block_chain(form, fallback));
        for layer in &layers {
            // A straight copy: `passthrough_form` has already established that each of these levels
            // is exactly what `format` implies, so the upload's own slicing cannot disagree.
            for level in layer.chain.mips.iter().take(LAYER_MIP_COUNT as usize) {
                data.extend_from_slice(level);
            }
        }
        debug_assert_eq!(data.len(), (layers.len() + 1) * per_layer);
        return PackedLayers {
            data,
            format: block_color_format(form),
            mip_count: LAYER_MIP_COUNT,
        };
    }

    let fb = solid_layer_chain(fallback);
    let mip_count = fb.mip_count;
    let mut data = fb.chain;
    for layer in layers {
        let matte = layer.matte;
        // `into_rgba8` is free for a chain that was never blocks and is the decode we were trying to
        // avoid for one that was — but it cannot fail, so this path is always available.
        let mut packed = chain_to_layer(layer.chain.into_rgba8(), LAYER_TEX_SIZE);
        if matte {
            packed
                .chain
                .iter_mut()
                .skip(3)
                .step_by(4)
                .for_each(|a| *a = 0);
        }
        data.extend_from_slice(&packed.chain);
    }
    PackedLayers {
        data,
        format: color_format(),
        mip_count,
    }
}

/// Bytes one array level occupies per layer in `form` — the arithmetic the eligibility check, the
/// packer and the fallback synthesiser all have to agree on, stated once.
fn form_level_bytes(form: BlpTexels, level: u32) -> usize {
    let w = (LAYER_TEX_SIZE >> level).max(1);
    form.level_bytes(w, w)
}

/// One solid-colour 4x4 block in `form`.
///
/// The colour half is a DXT1 colour block with `c0` = the colour, `c1` = 0 and every 2-bit index 0,
/// so all 16 texels read `c0` — quantised to RGB565, which is what a solid colour costs in any block
/// form. `Bc2`/`Bc3` carry the alpha exactly (explicit 4-bit / a constant 8-bit endpoint pair).
///
/// **`Bc1` cannot carry alpha at all**, so a `Bc1` tile's placeholder samples as opaque and would
/// take the sun sheen the `Rgba8Unorm` placeholder (alpha 0) suppresses. That is accepted, not
/// overlooked: layer 0 is only ever sampled when a BLP named by MTEX fails to read, which no healthy
/// install does — the census resolved all 1 048 `Tileset\` names — and it is a placeholder either way.
fn solid_block(form: BlpTexels, rgba: [u8; 4]) -> Vec<u8> {
    let c = ((rgba[0] as u16 >> 3) << 11) | ((rgba[1] as u16 >> 2) << 5) | (rgba[2] as u16 >> 3);
    let color = [c as u8, (c >> 8) as u8, 0, 0, 0, 0, 0, 0];
    let mut block = match form {
        // DXT3: eight bytes of explicit 4-bit alpha, two texels per byte.
        BlpTexels::Bc2 => vec![(rgba[3] >> 4) * 0x11; 8],
        // DXT5: `a0 == a1` and every 3-bit index 0, so every texel reads `a0` under either mode.
        BlpTexels::Bc3 => vec![rgba[3], rgba[3], 0, 0, 0, 0, 0, 0],
        BlpTexels::Bc1 | BlpTexels::Rgba8Unorm => Vec::new(),
    };
    block.extend_from_slice(&color);
    block
}

/// A solid-colour block chain at [`LAYER_TEX_SIZE`]² with [`LAYER_MIP_COUNT`] levels — the block-form
/// twin of [`solid_layer_chain`], for layer 0 of a passthrough array.
fn solid_block_chain(form: BlpTexels, rgba: [u8; 4]) -> Vec<u8> {
    let block = solid_block(form, rgba);
    let mut out = Vec::new();
    for level in 0..LAYER_MIP_COUNT {
        // Levels below 4x4 still occupy one whole block — `form_level_bytes` rounds up, which is
        // exactly what the authored chains next to this one do at their 2x2 tail.
        for _ in 0..(form_level_bytes(form, level) / block.len()) {
            out.extend_from_slice(&block);
        }
    }
    out
}

/// A solid-colour layer chain at [`LAYER_TEX_SIZE`]² with [`LAYER_MIP_COUNT`] levels — the per-tile
/// array's fallback layer 0 (a solid colour downsamples to itself, so every mip is the same colour).
pub(crate) fn solid_layer_chain(rgba: [u8; 4]) -> LayerTexture {
    let mut chain = Vec::with_capacity(mip_chain_byte_size(LAYER_TEX_SIZE, LAYER_MIP_COUNT));
    for level in 0..LAYER_MIP_COUNT {
        let w = (LAYER_TEX_SIZE >> level).max(1);
        for _ in 0..(w * w) {
            chain.extend_from_slice(&rgba);
        }
    }
    LayerTexture {
        chain,
        mip_count: LAYER_MIP_COUNT,
    }
}

/// Total bytes for a mip pyramid of `mip_count` levels starting at `top²` RGBA8.
pub(crate) fn mip_chain_byte_size(top: u32, mip_count: u32) -> usize {
    (0..mip_count)
        .map(|i| {
            let w = (top >> i).max(1);
            (w * w * 4) as usize
        })
        .sum()
}

/// Append `src` (RGBA8 `sw × sh`) resized to `dw × dh` to `out` using `NEAREST` — pure texel
/// replication/decimation, so gamma-encoded bytes pass through unchanged (no averaging → no
/// darkening). Identity at `(sw, sh) == (dw, dh)`.
pub(crate) fn extend_nearest(out: &mut Vec<u8>, src: &[u8], sw: u32, sh: u32, dw: u32, dh: u32) {
    if sw == dw && sh == dh {
        out.extend_from_slice(src);
        return;
    }
    let Some(buf) = image::RgbaImage::from_raw(sw, sh, src.to_vec()) else {
        out.extend(std::iter::repeat_n(0u8, (dw * dh * 4) as usize));
        return;
    };
    let resized = image::imageops::resize(&buf, dw, dh, image::imageops::FilterType::Nearest);
    out.extend_from_slice(resized.as_raw());
}

/// Stack the tile's ground textures into a repeating, mipmapped `2d_array`. `rgba` holds each layer's
/// full `mip_levels`-deep chain (LayerMajor order); `layer_count` layers at `size²` mip 0.
pub(crate) fn layer_array_image(size: u32, layer_count: u32, packed: PackedLayers) -> Image {
    let PackedLayers {
        data,
        format,
        mip_count,
    } = packed;
    let mut image = array_image(size, layer_count, format);
    image.data = Some(data);
    image.texture_descriptor.mip_level_count = mip_count;
    image.data_order = TextureDataOrder::LayerMajor;
    // Ground is the surface the filter policy costs the most on — a tiling texture at a grazing
    // angle is the anisotropy axis's worst case, and it fills most of the frame. The reference
    // does not let this lane choose: both values come from the process globals
    // ([`crate::tex_filter`]) — trilinear with anisotropy off, which is what `hwDetect` hands a
    // virgin install (1645).
    let filter = crate::tex_filter::tex_filter();
    image.sampler = ImageSampler::Descriptor(ImageSamplerDescriptor {
        address_mode_u: ImageAddressMode::Repeat,
        address_mode_v: ImageAddressMode::Repeat,
        mag_filter: ImageFilterMode::Linear,
        min_filter: ImageFilterMode::Linear,
        mipmap_filter: filter.mipmap_filter(),
        anisotropy_clamp: filter.anisotropy_clamp(),
        ..default()
    });
    image
}

/// Stack `layer_count` per-chunk alpha maps (each `size²`, concatenated) into a linear `2d_array` —
/// the tile's blend weights (R/G/B = layers 1/2/3 opacity). Non-colour, so `Rgba8Unorm`.
pub(crate) fn alpha_array_image(size: u32, layer_count: u32, rgba: Vec<u8>) -> Image {
    let mut image = array_image(size, layer_count, TextureFormat::Rgba8Unorm);
    image.data = Some(rgba);
    image
}

/// Stack `layer_count` MCSH shadow maps (each `size²`, one byte/texel) into a single-channel
/// `2d_array` — WoW's pre-baked static terrain shadows (`R` = shadowed, 0 = lit).
pub(crate) fn shadow_array_image(size: u32, layer_count: u32, data: Vec<u8>) -> Image {
    let mut image = array_image(size, layer_count, TextureFormat::R8Unorm);
    image.data = Some(data);
    image
}

/// Build a `2d_array` `Image` from concatenated per-layer bytes, with a `D2Array` view so the
/// `dimension = "2d_array"` bindings resolve.
///
/// `RenderAssetUsages::RENDER_WORLD`: the render world takes the bytes on extract — a tile's
/// three arrays are megabytes each, and nothing reads them main-side (they flow into the terrain
/// material as handles; the minimap, collider, clutter all derive from other sources). The
/// default usage cloned every array on landing AND kept a main-world copy resident per tile —
/// pure cost on both the B181 landing frame and the resident-set memory.
fn array_image(size: u32, layer_count: u32, format: TextureFormat) -> Image {
    // `new_uninit`, not `new`: `Image::new`'s length assert is written for uncompressed formats
    // (it skips itself when `pixel_size()` errors, which is every BC format) and it would force a
    // mip-0-sized dummy allocation on every tile just to be thrown away. The caller sets `data`.
    // Same reasoning, same call, as the model lane's `world_art_image` (`blp.rs`).
    let mut image = Image::new_uninit(
        Extent3d {
            width: size,
            height: size,
            depth_or_array_layers: layer_count,
        },
        TextureDimension::D2,
        format,
        RenderAssetUsages::RENDER_WORLD,
    );
    image.texture_view_descriptor = Some(TextureViewDescriptor {
        dimension: Some(TextureViewDimension::D2Array),
        ..default()
    });
    image
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A synthetic BLP mip chain: `mips` authored levels of a solid grey fill at `size²`.
    fn synthetic_chain(size: u32, mips: u32) -> BlpMipChain {
        let levels = (0..mips)
            .map(|i| {
                let w = (size >> i).max(1);
                vec![200u8; (w * w * 4) as usize]
            })
            .collect();
        BlpMipChain {
            texels: benilla_formats::BlpTexels::Rgba8Unorm,
            width: size,
            height: size,
            mips: levels,
        }
    }

    #[test]
    fn chain_to_layer_packs_a_native_256_blp_to_the_full_chain() {
        let layer = chain_to_layer(synthetic_chain(256, 8), LAYER_TEX_SIZE);
        assert_eq!(layer.mip_count, LAYER_MIP_COUNT);
        assert_eq!(
            layer.chain.len(),
            mip_chain_byte_size(LAYER_TEX_SIZE, LAYER_MIP_COUNT)
        );
    }

    #[test]
    fn chain_to_layer_upsamples_a_small_blp_without_darkening() {
        // A 64² BLP packed to 256²: the top levels are NEAREST-upsampled. A solid 200 in must come
        // out solid 200 — averaging (the C2 bug) would dim it below 200.
        let layer = chain_to_layer(synthetic_chain(64, 7), 256);
        assert_eq!(layer.chain.len(), mip_chain_byte_size(256, LAYER_MIP_COUNT));
        assert!(
            layer.chain.iter().all(|&b| b == 200),
            "NEAREST upsample must preserve the authored gamma bytes (no averaging)"
        );
    }

    #[test]
    fn solid_layer_chain_is_one_colour_at_every_mip() {
        let layer = solid_layer_chain([10, 20, 30, 40]);
        assert_eq!(
            layer.chain.len(),
            mip_chain_byte_size(LAYER_TEX_SIZE, LAYER_MIP_COUNT)
        );
        assert!(layer.chain.chunks_exact(4).all(|px| px == [10, 20, 30, 40]));
    }

    #[test]
    fn layer_array_image_has_the_expected_shape() {
        let bytes = vec![0u8; 3 * mip_chain_byte_size(LAYER_TEX_SIZE, LAYER_MIP_COUNT)];
        let img = layer_array_image(
            LAYER_TEX_SIZE,
            3,
            PackedLayers {
                data: bytes,
                format: color_format(),
                mip_count: LAYER_MIP_COUNT,
            },
        );
        assert_eq!(img.texture_descriptor.size.width, LAYER_TEX_SIZE);
        assert_eq!(img.texture_descriptor.size.depth_or_array_layers, 3);
        assert_eq!(img.texture_descriptor.mip_level_count, LAYER_MIP_COUNT);
    }

    /// A synthetic block chain: `mips` authored levels at `size²` in `form`, padded to whole blocks
    /// exactly as `benilla_blp::decode_native` delivers them.
    fn block_chain(form: BlpTexels, size: u32, mips: u32) -> BlpMipChain {
        let levels = (0..mips)
            .map(|i| {
                let w = (size >> i).max(1);
                vec![0u8; form.level_bytes(w, w)]
            })
            .collect();
        BlpMipChain {
            texels: form,
            width: size,
            height: size,
            mips: levels,
        }
    }

    fn raw(form: BlpTexels, size: u32, mips: u32, matte: bool) -> RawLayer {
        RawLayer {
            chain: block_chain(form, size, mips),
            matte,
        }
    }

    /// The whole eligibility rule, clause by clause — each `None` here is a tile that keeps paying
    /// 4 bytes a texel, so each one is worth stating.
    #[test]
    fn a_tile_passes_its_blocks_through_only_when_every_clause_holds() {
        let ok = || {
            vec![
                raw(BlpTexels::Bc2, 256, 8, false),
                raw(BlpTexels::Bc2, 256, 8, false),
            ]
        };
        assert_eq!(passthrough_form(&ok(), true), Some(BlpTexels::Bc2));

        // No device support (every headless test, and `WOW_NO_BC=1`).
        assert_eq!(passthrough_form(&ok(), false), None);
        // Mixed block forms — one array, one format. This is the common mixed tile: a `_s` variant
        // is DXT3 while a base without one is DXT1 (413 of 416 pairs in the install).
        let mixed = vec![
            raw(BlpTexels::Bc1, 256, 8, false),
            raw(BlpTexels::Bc2, 256, 8, false),
        ];
        assert_eq!(passthrough_form(&mixed, true), None);
        // Not natively 256² — reaching the array size is a NEAREST resample, a per-texel write.
        let small = vec![raw(BlpTexels::Bc2, 128, 7, false)];
        assert_eq!(passthrough_form(&small, true), None);
        // A short chain would have to repeat a level at the wrong size — the same resample.
        let short = vec![raw(BlpTexels::Bc2, 256, 5, false)];
        assert_eq!(passthrough_form(&short, true), None);
        // A matte layer needs its alpha stomped to 0, which is a per-texel write.
        let matte = vec![raw(BlpTexels::Bc2, 256, 8, true)];
        assert_eq!(passthrough_form(&matte, true), None);
        // Raw1/Raw3 tilesets have no block form at all.
        let raw1 = vec![RawLayer {
            chain: synthetic_chain(256, 8),
            matte: false,
        }];
        assert_eq!(passthrough_form(&raw1, true), None);
        // A tile with no layers at all is the fallback-only tile — nothing to pass through.
        assert_eq!(passthrough_form(&[], true), None);
    }

    /// The bug 1626 shipped for twenty minutes was blocks uploaded under a format that implied a
    /// different byte count. This asserts the pairing directly, for every block form: the packed
    /// buffer must be exactly what `format` says a `LAYER_TEX_SIZE²` × `mip_count` × `layers` array
    /// holds — nothing else can be sliced out of it correctly.
    #[test]
    fn a_packed_block_array_is_exactly_the_size_its_format_implies() {
        for form in [BlpTexels::Bc1, BlpTexels::Bc2, BlpTexels::Bc3] {
            let layers = vec![raw(form, 256, 8, false), raw(form, 256, 8, false)];
            // A level that lies about its size must not reach the packer: it would corrupt every
            // layer after it in the array rather than fail (1626's own twenty-minute bug).
            let mut short = raw(form, 256, 8, false);
            short.chain.mips[3].truncate(4);
            assert_eq!(passthrough_form(&[short], true), None, "{form:?}");
            let packed = pack([107, 133, 82, 0], layers, true);
            assert_eq!(packed.format, block_color_format(form));
            assert_eq!(packed.mip_count, LAYER_MIP_COUNT);
            let per_layer: usize = (0..LAYER_MIP_COUNT)
                .map(|i| form_level_bytes(form, i))
                .sum();
            // 3 layers: the synthesised fallback at index 0, then the two real ones.
            assert_eq!(packed.data.len(), 3 * per_layer, "{form:?}");
            // And the point of the whole change, pinned: DXT1 is 0.5 bytes a texel and DXT3/DXT5
            // are 1, against `Rgba8Unorm`'s 4. (The sub-4x4 tail mips cost a whole block in either
            // form, which is the entire 0.01 the ratio falls short of the texel arithmetic.)
            let decoded = 3 * mip_chain_byte_size(LAYER_TEX_SIZE, LAYER_MIP_COUNT);
            let ratio = decoded as f64 / packed.data.len() as f64;
            let want = if form == BlpTexels::Bc1 { 8.0 } else { 4.0 };
            assert!(
                (ratio - want).abs() < 0.01,
                "{form:?} packs {ratio:.3}x smaller than the decoded array, expected {want}x"
            );
        }
    }

    /// Layer 0 is synthesised, not read, so it is the one part of a passthrough array whose bytes we
    /// author ourselves — decode them back and check they are the colour we asked for.
    #[test]
    fn the_synthesised_fallback_block_decodes_to_its_colour() {
        let rgba = [107u8, 133, 82, 0];
        for form in [BlpTexels::Bc1, BlpTexels::Bc2, BlpTexels::Bc3] {
            let chain = solid_block_chain(form, rgba);
            let per_layer: usize = (0..LAYER_MIP_COUNT)
                .map(|i| form_level_bytes(form, i))
                .sum();
            assert_eq!(chain.len(), per_layer, "{form:?}");
            let top = BlpMipChain {
                texels: form,
                width: LAYER_TEX_SIZE,
                height: LAYER_TEX_SIZE,
                mips: vec![chain[..form.level_bytes(LAYER_TEX_SIZE, LAYER_TEX_SIZE)].to_vec()],
            }
            .into_rgba8()
            .mips
            .remove(0);
            // RGB565 is what a solid colour costs in any block form; assert within one quantisation
            // step per channel rather than pretending the round trip is exact.
            for px in top.chunks_exact(4) {
                for (got, want) in px[..3].iter().zip(&rgba[..3]) {
                    assert!(
                        got.abs_diff(*want) <= 8,
                        "{form:?}: {got} is not {want} within an RGB565 step"
                    );
                }
            }
            // Alpha is the sheen mask: `Bc2`/`Bc3` carry the requested 0; `Bc1` has no alpha channel
            // and samples opaque, which is the documented limitation of the placeholder.
            let alpha_ok = match form {
                BlpTexels::Bc1 => true,
                _ => top.chunks_exact(4).all(|px| px[3] == rgba[3]),
            };
            assert!(alpha_ok, "{form:?} must carry the fallback's alpha");
        }
    }

    /// The decoded path must still be byte-for-byte what this lane always produced — including the
    /// matte stomp, which moved out of the ADT loader and into `pack`.
    #[test]
    fn the_decoded_path_still_stomps_a_matte_layers_alpha() {
        let layers = vec![
            RawLayer {
                chain: synthetic_chain(256, 8),
                matte: true,
            },
            RawLayer {
                chain: synthetic_chain(256, 8),
                matte: false,
            },
        ];
        let packed = pack([107, 133, 82, 0], layers, true);
        assert_eq!(packed.format, color_format());
        let per_layer = mip_chain_byte_size(LAYER_TEX_SIZE, LAYER_MIP_COUNT);
        assert_eq!(packed.data.len(), 3 * per_layer);
        let matte = &packed.data[per_layer..2 * per_layer];
        assert!(
            matte.iter().skip(3).step_by(4).all(|&a| a == 0),
            "a layer with no `_s` variant must carry a zero sheen mask"
        );
        let sheened = &packed.data[2 * per_layer..];
        assert!(
            sheened.iter().skip(3).step_by(4).all(|&a| a == 200),
            "a layer that found its `_s` variant keeps the authored mask"
        );
    }

    #[test]
    fn alpha_and_shadow_arrays_have_the_expected_shape_and_format() {
        let alpha = alpha_array_image(64, 2, vec![0u8; 2 * 64 * 64 * 4]);
        assert_eq!(alpha.texture_descriptor.size.depth_or_array_layers, 2);
        assert_eq!(alpha.texture_descriptor.format, TextureFormat::Rgba8Unorm);
        let shadow = shadow_array_image(64, 2, vec![0u8; 2 * 64 * 64]);
        assert_eq!(shadow.texture_descriptor.size.depth_or_array_layers, 2);
        assert_eq!(shadow.texture_descriptor.format, TextureFormat::R8Unorm);
    }
}
