//! The `ColorSelect` method surface — the `CSimpleColorSelect` widget behavior over the kind tag
//! (factory `0x6eef90`; LoadXML `0x78b3f0`, script-map `0x78b4f0`, RF-28
//! `rf28-typed-widget-loadxml.md`). The widget holds one colour and fires `OnColorSelect` (its own
//! script slot, `+0x338`) when that colour is set.
//!
//! **Why this is engine-side and not four lines of Lua on `ColorPickerFrame`.** The corpus creates
//! its own: `TipBuddy.xml` declares two `<ColorSelect>` frames (`TBColorPickerFrame`,
//! `TBColorPickerFrame_Text`), each with its own `<OnColorSelect>` handler, and drives them with
//! `SetColorRGB`/`GetColorRGB`. A method table hung on the one frame `assets/ui` ships would leave
//! those two with a widget that has no methods — the "privileged built-in" failure the `.toc`
//! header names. So it lives with `Slider`/`StatusBar`, in the per-kind dispatcher.
//!
//! **The colour law is byte-verified, and it is not what it looks like.** This module was first
//! written against the obvious model — store three RGB bytes, hand them back — and a §5 cross-check
//! dispatched into wow-re for exactly this question corrected it
//! (`system/ui/scratch/colorselect-color-law.md`, 2026-08-11: three independent derivations plus an
//! emulated Unicorn oracle over the four helpers' own bytes). Two corrections, both load-bearing:
//!
//! 1. **The state is HSV `f32`, not RGB** — see [`ColorSelectState`] for the members and why.
//! 2. **The round trip is not the identity.** Inbound and outbound use *different* quantizers
//!    (round-half-up vs floor), so `SetColorRGB` → `GetColorRGB` returns a channel one step low on
//!    **9.7527 % of all 256³ reachable colours** — and, because the map is idempotent-free, the
//!    FrameXML idiom `r,g,b = f:GetColorRGB() … f:SetColorRGB(r,g,b)` **ratchets** a channel
//!    downward one step per cycle. `SetColorRGB(0, 1, 1)` fires `OnColorSelect(0, 254/255, 1)`.
//!    Every Ace2/Dewdrop colour option is that idiom, once per open-and-accept, so this is visible
//!    behaviour, not a curiosity — it is transcribed because it is what the client computes, and
//!    [`ColorSelectState`]'s docs record the one-line change that would undo it if it ever must go.
//!
//! **`SetColorRGB` fires `OnColorSelect`, synchronously, on every call.** VERIFIED at the bytes:
//! `0x78ed01 call 0x78bae0` is a plain fall-through of the last basic block, and inside it the only
//! conditional (`0x78bafd`) tests whether a handler is *bound*. There is deliberately **no
//! change-gate** — the contrast with [`crate::widget::SliderState::store_value`] is real and was
//! verified the other way in the same pass (`CSimpleSlider::SetValue 0x789930` skips on equal at
//! `0x789a16`): two sibling widgets in one band, opposite gating. It matters here because a caller
//! re-setting the colour it already holds still expects its `func` to run — which is exactly how a
//! Dewdrop colour row opens, and how the reference's own `ColorPickerFrame.xml` paints its preview
//! swatch (nothing else ever writes it).
//!
//! **NOT carried, and each waits for a customer (decision 1195):** `SetColorHSV`/`GetColorHSV`
//! (`0x78e920`/`0x78ea00`) — zero callers in the 218-addon corpus, though the state they would read
//! and write is now the right shape for them (`SetColorHSV` stores three *raw* `f32` — no clamp, no
//! quantize, zero `fcom` in its body — and fires the same slot); and the four wheel/value texture
//! accessors `SetColorWheelTexture` `0x78de90` / `SetColorWheelThumbTexture` `0x78e160` /
//! `SetColorValueTexture` `0x78e450` / `SetColorValueThumbTexture` `0x78e720` (+ the getters
//! `0x78dd80`/`0x78e070`), which address art this engine cannot draw: the wheel and the value strip
//! are generated by the client, not loaded — their `<ColorWheelTexture>`/`<ColorValueTexture>`
//! elements carry no `file=` at all. See `assets/ui/ColorPickerFrame.xml`'s header for what that
//! costs the window.

use mlua::{Lua, Table, Value};

use super::object::frame_handle_of;
use super::{event, Model};
use crate::widget::{ColorSelectState, KindState};

/// Registry key of the ColorSelect method table (the MAXCSTACK discipline: Lua-side root, named
/// key).
pub(super) const REG_COLORSELECT_METHODS: &str = "__benilla_colorselect_methods";

/// Run `f` over a frame's ColorSelect state under one short write borrow. Errors if `this` is not a
/// live ColorSelect (unreachable through the kind dispatcher, but the method table is a plain Lua
/// value — a caller could fish it out and misapply it).
fn with_colorselect<T>(
    lua: &Lua,
    this: &Table,
    f: impl FnOnce(&mut ColorSelectState) -> T,
) -> mlua::Result<T> {
    let h = frame_handle_of(lua, this)?;
    let mut model = lua.app_data_mut::<Model>().expect("model app_data");
    let frame = model
        .arena
        .frame_mut(h)
        .ok_or_else(|| mlua::Error::runtime("stale frame handle"))?;
    match &mut frame.kind_state {
        KindState::ColorSelect(s) => Ok(f(s)),
        _ => Err(mlua::Error::runtime("not a ColorSelect")),
    }
}

pub(super) fn install(lua: &Lua) -> mlua::Result<()> {
    let m = lua.create_table()?;

    m.set(
        "SetColorRGB",
        lua.create_function(|lua, (this, r, g, b): (Table, f64, f64, f64)| {
            // Store through the client's quantize, then fire with what the widget now *holds* —
            // the round-tripped values, identical to the next GetColorRGB, not the raw arguments.
            let (qr, qg, qb) = with_colorselect(lua, &this, |s| {
                s.set_rgb(r, g, b);
                s.rgb_f64()
            })?;
            fire_color_select(lua, &this, qr, qg, qb)
        })?,
    )?;
    m.set(
        "GetColorRGB",
        lua.create_function(|lua, this: Table| with_colorselect(lua, &this, |s| s.rgb_f64()))?,
    )?;

    lua.set_named_registry_value(REG_COLORSELECT_METHODS, m)?;
    Ok(())
}

/// Fire `OnColorSelect(self, r, g, b)` — the widget's own script slot (`+0x338`, RF-28). Fired
/// outside the model borrow; a handler error goes to [`Model::errors`] rather than back to the
/// setter's caller, the same posture as the Slider's `OnValueChanged`.
fn fire_color_select(lua: &Lua, this: &Table, r: f64, g: f64, b: f64) -> mlua::Result<()> {
    let id = {
        let h = frame_handle_of(lua, this)?;
        let mut model = lua.app_data_mut::<Model>().expect("model app_data");
        model.frame_id(h)
    };
    if let Err(e) = event::fire_widget_handler(
        lua,
        id,
        "OnColorSelect",
        vec![Value::Number(r), Value::Number(g), Value::Number(b)],
    ) {
        lua.app_data_mut::<Model>()
            .expect("model app_data")
            .errors
            .push(e.to_string());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use crate::script::UiScript;
    use crate::widget::ColorSelectState;

    /// A `ColorSelect` starts **white** (the ctor's `H=0, S=0, V=1`), not black. A zero-init store
    /// would have made it black, which is the tell that the state is HSV and not RGB.
    #[test]
    fn a_fresh_color_select_is_white() {
        let s = UiScript::new().unwrap();
        s.run(r#"cs = CreateFrame("ColorSelect", "TestColorSelectNew")"#)
            .unwrap();
        let (r, g, b): (f64, f64, f64) = s.eval("return cs:GetColorRGB()").unwrap();
        assert_eq!((r, g, b), (1.0, 1.0, 1.0));
    }

    /// **The round trip is not the identity, and the deviation is the client's.** `(0, 1, 1)` — cyan,
    /// a two-channel tie at the maximum — comes back with green one step low, the exact witness
    /// wow-re's exhaustive sweep names. Greys are its control class and never lose.
    #[test]
    fn the_round_trip_loses_exactly_one_step_on_the_witness_colour() {
        let s = UiScript::new().unwrap();
        s.run(r#"cs = CreateFrame("ColorSelect", "TestColorSelectRT")"#)
            .unwrap();
        s.run("cs:SetColorRGB(0, 1, 1)").unwrap();
        let (r, g, b): (f64, f64, f64) = s.eval("return cs:GetColorRGB()").unwrap();
        assert_eq!(r, 0.0);
        assert_eq!(g, 254.0 / 255.0, "the tied maximum loses one step");
        assert_eq!(b, 1.0);

        // The control: a grey survives exactly (the `S == 0` leg copies V and never reads hue).
        for byte in [0u8, 1, 64, 128, 254, 255] {
            let v = f64::from(byte) / 255.0;
            s.run(&format!("cs:SetColorRGB({v}, {v}, {v})")).unwrap();
            let (gr, gg, gb): (f64, f64, f64) = s.eval("return cs:GetColorRGB()").unwrap();
            assert_eq!((gr, gg, gb), (v, v, v), "grey {byte} must survive exactly");
        }
    }

    /// **And it ratchets.** The FrameXML idiom — read the colour back, hand it straight to
    /// `SetColorRGB` — re-applies the same lossy map instead of settling. wow-re's pin: `(0, 8, 132)`
    /// walks to `(0, 0, 132)` in eight cycles. Every Ace2/Dewdrop colour option is that idiom, once
    /// per open-and-accept, so this is the shape of a real player-visible drift and it is deliberate.
    #[test]
    fn the_read_back_ratchets_a_channel_downward() {
        let s = UiScript::new().unwrap();
        s.run(r#"cs = CreateFrame("ColorSelect", "TestColorSelectRatchet")"#)
            .unwrap();
        s.run("cs:SetColorRGB(0/255, 8/255, 132/255)").unwrap();
        let mut seen = Vec::new();
        for _ in 0..8 {
            let g: f64 = s
                .eval("local r, g, b = cs:GetColorRGB() cs:SetColorRGB(r, g, b) return g")
                .unwrap();
            seen.push((g * 255.0).round() as u8);
        }
        assert_eq!(
            seen,
            vec![7, 6, 5, 4, 3, 2, 1, 0],
            "one step down per cycle, to a fixed point at 0"
        );
        // The fixed point holds — it is a ratchet, not a runaway.
        let g: f64 = s
            .eval("local r, g, b = cs:GetColorRGB() cs:SetColorRGB(r, g, b) return g")
            .unwrap();
        assert_eq!(g, 0.0);
    }

    /// The two quantizers, directly. A is round-half-up and clamps; B is a floor with no clamp.
    #[test]
    fn the_two_quantizers_disagree_in_the_verified_way() {
        // A — inbound. The clamp is part of it, so `2` is white and `-1` is black, not a wrapped byte.
        assert_eq!(ColorSelectState::quantize_a(-1.0), 0);
        assert_eq!(ColorSelectState::quantize_a(0.0), 0);
        assert_eq!(ColorSelectState::quantize_a(1.0), 255);
        assert_eq!(ColorSelectState::quantize_a(2.0), 255);
        // The half-up bias: 0.5·255 = 127.5, +0.5 = 128.0, truncated = 128.
        assert_eq!(ColorSelectState::quantize_a(0.5), 128);

        // B — outbound. Endpoints agree with A; a value a hair below a boundary does NOT.
        assert_eq!(ColorSelectState::quantize_b(0.0), 0);
        assert_eq!(ColorSelectState::quantize_b(1.0), 255);
        assert_eq!(ColorSelectState::quantize_b(0.5), 127, "floor, not half-up");
        assert_ne!(
            ColorSelectState::quantize_b(0.5),
            ColorSelectState::quantize_a(0.5),
            "the disagreement IS the mechanism behind the drift"
        );
        // No clamp on B — out of range wraps mod 256 (reachable only through SetColorHSV).
        assert_eq!(ColorSelectState::quantize_b(-0.001), 255);
    }

    /// `SetColorRGB` fires `OnColorSelect` with the colour the widget now holds, and fires **again**
    /// when the same colour is set — no change-gate (the module doc's byte-verified reason).
    #[test]
    fn set_color_rgb_fires_on_color_select_every_time() {
        let s = UiScript::new().unwrap();
        s.run(
            r#"
            fired = {}
            cs = CreateFrame("ColorSelect", "TestColorSelect2")
            cs:SetScript("OnColorSelect", function()
                table.insert(fired, arg1 .. "," .. arg2 .. "," .. arg3)
            end)
        "#,
        )
        .unwrap();
        s.run("cs:SetColorRGB(1, 0, 0)").unwrap();
        s.run("cs:SetColorRGB(1, 0, 0)").unwrap();
        assert!(s.errors().is_empty(), "{:?}", s.errors());
        assert_eq!(s.eval::<usize>("return table.getn(fired)").unwrap(), 2);
        assert_eq!(s.eval::<String>("return fired[1]").unwrap(), "1,0,0");

        // The handler's arguments are bit-identical to a GetColorRGB() on the next line — the
        // binary reaches them through literally the same two calls, and so do we.
        s.run("fired = {} cs:SetColorRGB(0, 1, 1)").unwrap();
        let (from_handler, from_getter): (String, String) = s
            .eval("local r, g, b = cs:GetColorRGB() return fired[1], r .. \",\" .. g .. \",\" .. b")
            .unwrap();
        assert_eq!(from_handler, from_getter);
    }

    /// The methods are the ColorSelect's alone — a plain frame duck-types as *not* one, which is how
    /// `if frame.SetColorRGB then` reads in an addon.
    #[test]
    fn the_methods_do_not_leak_onto_other_kinds() {
        let s = UiScript::new().unwrap();
        s.run(r#"plain = CreateFrame("Frame", "TestPlainFrame")"#)
            .unwrap();
        assert!(s.eval::<bool>("return plain.SetColorRGB == nil").unwrap());
        assert!(s.eval::<bool>("return plain.GetColorRGB == nil").unwrap());
    }
}
