name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - ios-test
  pull_request:
    branches:
      - ios-test

jobs:
  ios:
    name: ios
    runs-on: macos-latest
    environment: ios
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.97.1
      - name: Install dependencies
        run: |
          brew install ldid
      - name: Build executable
        run: |
          rustup target add aarch64-apple-ios
          cd mobile
          xcodebuild \
          -project benilla.xcodeproj \
          -scheme benilla \
          -sdk iphoneos \
          -verbose \
          archive -archivePath ./benilla.xcarchive \
          CODE_SIGNING_REQUIRED=NO \
          AD_HOC_CODE_SIGNING_ALLOWED=YES \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM=XYZ0123456 \
          ORG_IDENTIFIER=org.benilla | xcpretty && exit ${PIPESTATUS[0]}
      - name: Fakesign app
        run: |
          cd mobile
          ldid -Sbenilla.entitlements benilla.xcarchive/Products/Applications/benilla.app/benilla
      - name: Build ipa
        run: |
          cd mobile
          mkdir Payload
          mkdir Payload/benilla.app
          cp -R benilla.xcarchive/Products/Applications/benilla.app/ Payload/benilla.app/
          zip -r ../benilla.ipa Payload
      - name: Cleanup
        run: |
          cd mobile
          rm -fr benilla.xcarchive
          rm -fr Payload
      - uses: actions/upload-artifact@v7
        with:
          name: benilla-ios
          path: |
            benilla.ipa

  release:
    name: release
    runs-on: ubuntu-latest
    environment: linux
    needs: [ios]
    steps:
      - uses: actions/checkout@v6

      - name: Set short git commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: assets
        run: |
          cd crates/benilla-app
          zip -r ../../assets.zip assets

      - uses: actions/download-artifact@v7
        with:
          name: benilla-ios
          path: "./benilla-ios"
      - run: |
          mv './benilla-ios/benilla.ipa' './benilla.ipa'

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          files: |
            benilla.ipa
            assets.zip
